### ISSUE TITLE
Reflection from Homework #9

### ISSUE THREAD

**Issue by statistical-lusardi** [ST541-Fall2020/statistical-lusardi-project-google-searches#7]
Return to your milestones set in Homework 5:  
@cwickham 

* How much progress have you made?

I have been reviewing my progress, but unfortunately my milestones have not been done on time.
* Have you reached the milestones on time?  Why or why not?
My biggest obstacle in the beginning I thought was to find the correct anchors that would scale my google searches to a normalized value. However, my biggest obstacle to date has been modifying the built-in functions that are used to collect data from google trends and scale them into usable information. The entire repository including the functions to work with the processed search data were specifically developed for the project at hand and is very difficult to translate to my work. 

To solve this, I put myself in contact with the Author Manuel Schmitz and we have been corresponding on how to fix these issues. It has been far more difficult on this front to change the functionality and automation of the scripts to work with data that I had specified. 

Review the [project rubric](https://canvas.oregonstate.edu/courses/1781180/assignments/8120989?module_item_id=20149541):  

* How would you grade yourself based on your project in its current form? 
Although it is very meticulously documented, It is not functioning so I would not pass it.

* What do you need to do before your presentation?  

* What do you need to do before the project due date?  
I need to scale the collected data by hand and break apart the scaling function into pieces, and reformat it for my collected trends data.

Once scaled, I can present my results for my correlated searches and restaurant visits per week.

This includes making more sub directories for the parts to this project.

* Are there things you need help from Charlotte or the TA on?

Unfortunately, the problems are so over-specific, it would be very difficult to bring someone up to speed on them. I will have to take this on my own

Make a plan for the next couple of weeks.  

I plan on following my milestones as the tasks are still relevant but have been taking longer than necessary to do so.

**Comment by cwickham** [comment]
I think you've run into a pretty common problem - a project looks really complete and documented on GitHub but when you dive into it, it much harder to reproduce and adapt that you expect.

We talked a little about this before, but now is probably a good time to step back and think about how to frame the report.  I don't really care if you've got code that completes what you set out to do, I more interested in a repo/project that documents and outlines what you did do, and your report reflects on what you learned from the experience.

**Comment by statistical-lusardi** [comment]
Thank you for your help!
